name = "serverless-woo-api"
type = "javascript"
zone_id = ""
account_id = "eb72da6777f630a3116117a141717763"
route = ""
workers_dev = true
compatibility_date = "2022-01-30"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
